name: tu_alimento_diario
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # Autenticaci√≥n
  google_sign_in: ^6.2.1

  # Estado / utils
  flutter_riverpod: ^2.5.1
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  firebase_app_check: ^0.3.2+10
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.12.0
  google_mobile_ads: ^5.1.0
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo_sin_fondo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo_sin_fondo.png
  image_path_android: assets/logo_launcher.png
  image_path_ios: assets/logo_sin_fondo.png
  adaptive_icon_foreground: assets/logo_launcher.png
  adaptive_icon_background: assets/icon_background.png
  min_sdk_android: 21
  remove_alpha_ios: true
